import {favorableReference} from './favorable.js?v=b1cae4b4be94';
import {roleOf,sleepingDirection} from './residence.js?v=b1cae4b4be94';
import {newHouse} from './core.js?v=b1cae4b4be94';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function buyerError(h){if(!h.buyingCity?.trim())return '请填写准备买房的城市。';if(h.purchaseBudget!==''&&h.purchaseBudget!=null&&(!Number.isFinite(Number(h.purchaseBudget))||Number(h.purchaseBudget)<=0||Number(h.purchaseBudget)>100000))return '购房总预算请填写有效万元数，或留空。';if(!Number.isInteger(Number(h.preferredRooms))||Number(h.preferredRooms)<1||Number(h.preferredRooms)>12)return '请选择需要的卧室数量。';return '';}
export function buyingAdvice(h,b){
 const favorable=favorableReference(b),sleep=sleepingDirection(b),role=roleOf(h),rooms=Number(h.preferredRooms)||2;
 const uses=({family:['家庭自住','客餐厅能让家人坐下交流，卧室与公共活动分开。','核对餐桌和沙发放下后，卧室通路仍然连续。'],rest:['安静休息','优先选卧室远离电梯井、主路和公共活动点的户型。','白天与晚间各到卧室窗边停留，分别听开窗和关窗后的声音。'],work:['居家工作','留出能固定使用的工作位，工作区与床分开。','书桌侧面有自然光，屏幕不直接朝窗；视频会议不占用家人必经路线。']})[h.buyingUse||'family'];
 return {favorable,role,sleep,headline:favorable.element?`选房先看格局，重点找能安置${sleep.directions.join('或')}向床头的卧室。`:`先按家庭用途筛房。${favorable.reason}，本次不指定个人方位。`,rows:[
 {title:'个人方位参考',text:favorable.element?`${favorable.reason}。看房时检查卧室能否安排床头朝${sleep.directions.join('或')}、靠实墙，并避开窗下和门口直视。`:`${favorable.reason}。先检查床头靠实墙、通行和安静程度，核对出生资料后再补个人方位。`,method:'这是八字扶抑的居住参考，不等同于整栋楼必须朝这个方向。'},
 {title:role.direction?`${role.direction} · ${role.gua}位 · ${role.name}`:'家庭空间分配',text:role.direction?`按《说卦》家庭取象，重点查看${role.direction}方是否有明显内凹、是否具备可用采光与活动空间。`:'先按实际常住成员分配房间，再看各方位的形体与用途。',method:'外边界只计封闭室内。拿到图纸后核对凹处是室外、管井还是未画清的墙线，再决定是否接受。'},
 {title:`${rooms}间卧室 · ${uses[0]}`,text:uses[1],method:uses[2]+(rooms===1?'单卧室户型尤其要把休息与工作分开。':'不要仅按房间数量判断，逐间试放床、柜后核对开门和通道。')},
 {title:'外部条件先现场核对',text:'在主卧窗、客厅窗和入户门分别观察；地图查清楼栋、道路和河流，再核实开口正对关系。',method:'记录所在楼层、遮光时段、车流噪声和对视。外部条件难以调整的房源，与其他候选房并排比较。'},
 {title:'看房时带走三份资料',text:'清晰户型图、八方位依据、带尺寸的平面资料。',method:`以${h.buyingCity}为查找范围${h.purchaseBudget?`，按你填写的总预算 ${h.purchaseBudget} 万元筛选`:'，先确定可承受的总预算'}。价格、产权与实际尺寸另行核对；取得候选图纸后再做住宅分析。`}
 ]};
}
export function buyerNeeds(h){const field=(title,key,extra='')=>`<label class="field"><span>${title}</span><input data-field="${key}" value="${e(h[key]||'')}" ${extra}></label>`;return `<section class="workspace intake-workspace buyer-workspace"><div class="intake-heading">准备买房 / 你的选房范围</div><div class="intake-panel"><p class="hint">还没有户型图，也可以先准备个人看房清单。</p>${field('准备买房的城市','buyingCity','maxlength="30"')}${field('购房总预算（万元，选填）','purchaseBudget','type="number" min="1" max="100000"')}<label class="field"><span>需要几间卧室</span><select data-field="preferredRooms">${Array.from({length:12},(_,i)=>`<option value="${i+1}" ${Number(h.preferredRooms)===i+1?'selected':''}>${i+1} 间</option>`).join('')}</select></label><label class="field"><span>主要居住需求</span><select data-field="buyingUse">${Object.entries({family:'家庭自住',rest:'安静休息',work:'居家工作'}).map(([k,v])=>`<option value="${k}" ${h.buyingUse===k?'selected':''}>${v}</option>`).join('')}</select></label><small>出生资料与清单只保存在本浏览器，可随时删除。</small></div><div class="wizard-bottom"><button class="btn ghost" data-action="buyer-prev">← 返回上一级</button><small>2 / 2</small><button class="btn primary" data-action="buyer-generate">生成选房建议 →</button></div></section>`;}
export function buyerReport(h,b){const a=buyingAdvice(h,b);return `<section class="workspace report-workspace buyer-report"><div class="page-heading"><h1>你的选房清单</h1><button class="btn ghost" data-action="buyer-edit">修改资料</button></div><p class="buyer-lead">${e(a.headline)}</p>${a.rows.map((r,i)=>`<section class="report-section"><span class="eyebrow">0${i+1}</span><h2>${e(r.title)}</h2><p>${e(r.text)}</p><p class="buyer-method"><b>看房时这样核对：</b>${e(r.method)}</p></section>`).join('')}<section class="report-section"><h2>找到候选房后，继续看宅</h2><p>带入这份出生资料，上传候选户型，核对红线、方位与家具。</p><button class="btn primary" data-action="buyer-candidate">新建候选房宅档 →</button><button class="text-link" data-action="buyer-delete">删除本机选房资料</button></section><p class="small-note">个人方位采用传统八字扶抑参考；选房需同时核对实际居住条件。</p></section>`;}
export function buyerToHouse(profile){const h=newHouse('compare');h.flowVersion=4;h.birth=structuredClone(profile.birth);h.householdRole=profile.householdRole||'';h.housingCity=profile.buyingCity||'';h.bedrooms=profile.preferredRooms||'';return h;}
// Separate database prevents profiles without a floorplan entering the residence archive.
async function database(){return new Promise((resolve,reject)=>{const r=indexedDB.open('guanzhai-buyer-v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('profiles');r.onerror=()=>reject(r.error);r.onsuccess=()=>resolve(r.result);});}
export async function buyerStorage(action,value){const db=await database();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('profiles',action==='get'?'readonly':'readwrite'),store=tx.objectStore('profiles'),request=action==='get'?store.get('current'):action==='put'?store.put(value,'current'):store.delete('current');let result;request.onsuccess=()=>result=request.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('选房资料未保存'));});}finally{db.close();}}
