import {insideRoom,roomAnchor} from './geometry.js?v=82168a3e723a';
import {rectangle,regionWithin} from './intake-validation.js?v=82168a3e723a';
import {CATALOG} from './catalog.js?v=82168a3e723a';
import {symbol} from './plan-symbols.js?v=82168a3e723a';
import {sleepingDirection,DIRECTIONS} from './residence.js?v=82168a3e723a';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mod=n=>(Number(n||0)%360+360)%360;
export const symbolSize=m=>.06*Math.max(.5,Math.min(3,Number(m.uiScale)||1));
export function markerBox(m,f){const r=symbolSize(m)/2,rx=r,ry=r*f.width/f.height,angle=mod(m.rotation)*Math.PI/180;const c=Math.abs(Math.cos(angle)),s=Math.abs(Math.sin(angle));return {x:m.x-rx*c-rx*s,y:m.y-ry*c-ry*s,w:2*rx*(c+s),h:2*ry*(c+s)};}
const overlap=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
const excluded=['kitchen','bath','stairs','balcony','yard','hall'];
function wallDistance(p,r,f){let best=Infinity;const ps=rectangle(r);for(let i=0;i<ps.length;i++){const a=ps[i],b=ps[(i+1)%ps.length],dx=(b.x-a.x)*f.width/f.height,dy=b.y-a.y,px=(p.x-a.x)*f.width/f.height,py=p.y-a.y,t=Math.max(0,Math.min(1,(px*dx+py*dy)/(dx*dx+dy*dy||1)));best=Math.min(best,Math.hypot(px-dx*t,py-dy*t));}return best;}
function backingAngle(p,r,f){let best=null,dist=Infinity;const ps=rectangle(r),aspect=f.width/f.height;for(let i=0;i<ps.length;i++){const a=ps[i],b=ps[(i+1)%ps.length],dx=(b.x-a.x)*aspect,dy=b.y-a.y,px=(p.x-a.x)*aspect,py=p.y-a.y,t=Math.max(0,Math.min(1,(px*dx+py*dy)/(dx*dx+dy*dy||1))),vx=dx*t-px,vy=dy*t-py,d=Math.hypot(vx,vy);if(d<dist){dist=d;best=mod(Math.round(Math.atan2(vx,-vy)*180/Math.PI/15)*15);}}return best;}
function utility(m,r,f,goals,b){const edge=wallDistance(m,r,f),openings=f.markers.filter(x=>['door','window'].includes(x.type)),near=Math.min(.3,...openings.map(x=>Math.hypot((m.x-x.x)*f.width/f.height,m.y-x.y))),anchor=roomAnchor(r),centre=Math.hypot(m.x-anchor.x,m.y-anchor.y);let extra=0;if(m.type==='bed'||m.type==='sofa'){const angle=mod(m.rotation)*Math.PI/180,offset=symbolSize(m)/2,head={x:m.x+Math.sin(angle)*offset,y:m.y-Math.cos(angle)*offset*f.width/f.height};extra=-wallDistance(head,r,f)*2;if(m.type==='bed'&&sleepingDirection(b).directions.includes(DIRECTIONS[Math.round(mod(m.rotation-f.north)/45)%8]))extra+=.04;}return near*2-edge*1.8+centre*.3+extra;}
export function conceptLayout(h,b){const moves=[],actions=[],zoneChanges=[],blocked=[];
 const goals=h.goals||[],wanted=new Set(['bed','desk','sofa','cabinet','bookshelf','diningTable']);
 for(const f of h.floors){const working=structuredClone(f.markers),rooms=f.rooms.filter(r=>!r.locked&&!excluded.includes(r.type));
  if(goals.some(g=>['work','study'].includes(g))&&!f.rooms.some(r=>r.type==='study')){const r=rooms.find(r=>r.type==='other'&&working.some(m=>m.type==='desk'&&insideRoom(m,r)));if(r){zoneChanges.push({floorId:f.id,roomId:r.id,from:{name:r.name,type:r.type},to:{name:r.name+' · 工作区',type:'study'}});actions.push({title:'将已有桌面的空闲区用于工作',where:f.name+' · '+r.name,text:'保留墙体、门窗和管线，把桌面与资料集中在这一区；试用后再决定是否添置收纳。',source:'已标功能区与书桌',kind:'zone'});}}
  const priority=m=>goals.includes('rest')&&m.type==='bed'||goals.some(g=>['study','work'].includes(g))&&m.type==='desk'||goals.includes('family')&&['sofa','diningTable'].includes(m.type)||goals.includes('wealth')&&['cabinet','bookshelf'].includes(m.type)?0:1;
  for(const m of [...working].sort((a,b)=>priority(a)-priority(b))){if(!wanted.has(m.type)||m.locked||CATALOG[m.type]?.fixed||h.keep?.includes(CATALOG[m.type]?.name))continue;const r=rooms.find(r=>insideRoom(m,r));if(!r)continue;
   let best=null,score=utility(m,r,f,goals,b)+.035;const others=working.filter(x=>x.id!==m.id&&x.type!=='rug'&&x.type!=='curtain');
   for(let yi=1;yi<20;yi++)for(let xi=1;xi<20;xi++){const to={x:r.x+r.w*xi/20,y:r.y+r.h*yi/20,rotation:mod(m.rotation)};if(['bed','sofa'].includes(m.type))to.rotation=backingAngle(to,r,f);const candidate={...m,...to},box=markerBox(candidate,f);if(Math.hypot(to.x-m.x,to.y-m.y)<.035||!regionWithin(box,rectangle(r))||f.boundary&&!regionWithin(box,f.boundary)||others.some(o=>overlap(box,markerBox(o,f))))continue;const s=utility(candidate,r,f,goals,b);if(s>score){best=to;score=s;}}
   if(!best){blocked.push({floorId:f.id,id:m.id,name:CATALOG[m.type].name,room:r.name});continue;}
   const from={x:m.x,y:m.y,rotation:mod(m.rotation)},move={floorId:f.id,id:m.id,type:m.type,from,to:best,reason:'让家具靠近边侧，避开已标门窗，留出中部活动空间'};moves.push(move);Object.assign(m,best);
   actions.push({title:`把${CATALOG[m.type].name}移到图中 ${moves.length} 号位置`,where:f.name+' · '+r.name,text:`${m.type==='bed'?'床头转向图中邻近墙面':m.type==='sofa'?'沙发背部朝向图中邻近墙面':'靠边安排'}，避开已标门窗，中部留给活动。先确认这面墙可用，再量家具与开门净空，按图试摆。`,source:'已标家具与房间轮廓',kind:'move',markerId:m.id});
  }
 }
 if(!moves.length&&!zoneChanges.length)actions.push({title:'本轮保留现状，不强行挪动家具',where:'全屋',text:'当前标注中没有找到更合适的可移动位置。检查家具是否已标、是否锁定，以及功能区范围；补齐后再推演。配色和实际干扰的处理仍可按建议进行。',source:'当前家具与可用范围',kind:'constraint'});
 return {moves,zoneChanges,actions,blocked};
}
export function layoutDrawing(f,p=null,after=false){
 const marks=structuredClone(f.markers),rooms=structuredClone(f.rooms),moves=(p?.moves||[]).filter(m=>m.floorId===f.id);
 if(after){for(const mv of moves){const m=marks.find(m=>m.id===mv.id);if(m)Object.assign(m,mv.to);}for(const z of p?.zoneChanges||[]){if(z.floorId===f.id){const r=rooms.find(r=>r.id===z.roomId);if(r)Object.assign(r,z.to);}}}
 const w=1000,h=w*f.height/f.width,poly=ps=>ps.map(q=>`${q.x*w},${q.y*h}`).join(' '),boundary=f.boundary||rectangle(f.bounds),prefix=`${after?'after':'before'}-${f.id}`;
 return `<svg class="layout-schematic" viewBox="0 0 ${w} ${h}" role="img" aria-label="${after?'优化后':'调整前'}的标注平面示意"><defs><marker id="${prefix}-arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0L6 3 0 6" fill="none" stroke="#a16621" stroke-width="1.4"/></marker></defs><rect width="${w}" height="${h}" fill="#eee9dd"/><polygon points="${poly(boundary)}" fill="#faf7ef" stroke="#805d4c" stroke-width="5"/>${rooms.map(r=>{const top={x:r.x+r.w/2,y:r.y+.045},a=insideRoom(top,r)?top:roomAnchor(r);return `<g><polygon points="${poly(rectangle(r))}" fill="#d8dfd145" stroke="#70796c" stroke-width="2"/><text x="${a.x*w}" y="${a.y*h}" text-anchor="middle" fill="#50594f" font-size="28">${e(r.name)}</text></g>`;}).join('')}${after?moves.map((m,i)=>`<g class="layout-move" data-move-id="${e(m.id)}"><circle cx="${m.from.x*w}" cy="${m.from.y*h}" r="20" fill="none" stroke="#a16621" stroke-width="2" stroke-dasharray="5 5"/><path d="M${m.from.x*w} ${m.from.y*h}L${m.to.x*w} ${m.to.y*h}" fill="none" stroke="#a16621" stroke-width="2.5" marker-end="url(#${prefix}-arrow)"/></g>`).join(''):''}${marks.map(m=>{const size=symbolSize(m)*w,changed=after&&moves.find(x=>x.id===m.id),ix=(p?.moves||[]).findIndex(x=>x.id===m.id);return `<g class="layout-marker ${changed?'changed':''}" data-marker-id="${e(m.id)}" data-x="${m.x}" data-y="${m.y}" data-rotation="${mod(m.rotation)}" transform="translate(${m.x*w} ${m.y*h})"><title>${e(CATALOG[m.type]?.name||'物件')}${changed?' · 已调整':''}</title><g transform="rotate(${mod(m.rotation)})"><rect x="${-size/2}" y="${-size/2}" width="${size}" height="${size}" rx="3" fill="${changed?'#ecd09a':'#eee9dd'}"/><g transform="translate(${-size/2} ${-size/2})" style="color:#344638">${symbol(m.type).replace('<svg ',`<svg width="${size}" height="${size}" `)}</g></g>${changed?`<circle cx="${size/2}" cy="${-size/2}" r="19" fill="#7d5422"/><text x="${size/2}" y="${-size/2+7}" text-anchor="middle" fill="white" font-size="22">${ix+1}</text>`:''}</g>`;}).join('')}<g transform="translate(45 55) rotate(${f.north||0})"><path d="M0 20V-15m0 0-7 12m7-12 7 12" stroke="#695a36" stroke-width="3"/><text x="0" y="-22" text-anchor="middle" font-size="18" fill="#695a36">北</text></g></svg>`;
}
