import {DIRECTIONS,EXTERNAL_TYPES,EXTERNAL_EFFECTS,mapSearch,normalizeEnvironment} from './residence.js?v=58bbea2826c4';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const opts=(map,val)=>Object.entries(map).map(([k,v])=>`<option value="${k}" ${k===val?'selected':''}>${e(v)}</option>`).join('');
export function editEnvironment(h,{modal,save,toast}){
 const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
 const blank=()=>({name:'',direction:'北',kind:'building',effect:'unknown',distance:'',source:'免费地图查找',position:'',url:'',note:''});
 const rows=(h.environment?.items||[]).map(x=>({...blank(),...x,direction:x.direction||DIRECTIONS[Math.round((x.bearing||0)/45)%8],distance:x.distance??'',...(h.environment?.status==='stale'?{effect:'unknown',position:''}:{})}));if(!rows.length)rows.push(blank());let index=0;
 const stash=()=>all('[data-environment]').forEach(el=>rows[index][el.dataset.environment]=el.value);
 const input=(key,placeholder='',type='text')=>`<input data-environment="${key}" aria-label="${placeholder}" type="${type}" value="${e(rows[index][key])}" placeholder="${placeholder}" maxlength="240">`;
 const show=()=>{
 modal('宅外周边 · 免费查找',`<div class="environment-editor"><p>${h.environment?.status==='stale'?'地址已修改，原记录已保留。请重新核对楼栋、方位和观察情况后再保存。':'以你的楼栋为中心查找，再到主要窗边核对。'}</p><a class="btn outline" href="${e(mapSearch(h))}" target="_blank" rel="noopener noreferrer">在高德查找住宅 ↗</a><small>点击后会在高德打开所填地址；不发送八字或户型图。</small><div class="environment-tabs">${rows.map((x,i)=>`<button data-env-index="${i}" class="${i===index?'selected':''}">${i+1}. ${e(x.name||'新记录')}</button>`).join('')}<button id="add-environment">＋ 添加</button></div><div class="form-grid"><label class="field"><span>所在方位</span><select data-environment="direction">${opts(Object.fromEntries(DIRECTIONS.map(x=>[x,x])),rows[index].direction)}</select></label><label class="field"><span>周边类型</span><select data-environment="kind">${opts(EXTERNAL_TYPES,rows[index].kind)}</select></label></div><label class="field"><span>地点或景物名称</span>${input('name','如：东侧道路 / 对面楼栋')}</label><label class="field"><span>实际观察</span><select data-environment="effect">${opts(EXTERNAL_EFFECTS,rows[index].effect)}</select></label><div class="form-grid"><label class="field"><span>观察位置</span>${input('position','如：客厅窗边')}</label><label class="field"><span>距离（米，选填）</span>${input('distance','不知道可留空','number')}</label></div><details><summary>来源与补充说明</summary><label class="field"><span>资料来源</span>${input('source','地图 / 现场观察')}</label><label class="field"><span>来源链接（选填）</span>${input('url','https://…','url')}</label><label class="field"><span>观察时间、楼栋与说明</span>${input('note','如：下午3点，12楼窗边观察')}</label></details><button class="text-link" id="remove-environment">删除这条记录</button><p class="hint">查找结果不会自动变成现场结论。观察情况不同，请分别记录。</p></div>`,`<button class="btn ghost" data-close>返回</button><button class="btn primary" id="save-environment">保存周边资料</button>`);
 all('[data-env-index]').forEach(el=>el.onclick=()=>{stash();index=Number(el.dataset.envIndex);show();});
 $('#add-environment').onclick=()=>{stash();if(rows.length>=24){toast('最多保存 24 条周边记录。');return;}rows.push(blank());index=rows.length-1;show();};
 $('#remove-environment').onclick=()=>{rows.splice(index,1);if(!rows.length)rows.push(blank());index=Math.min(index,rows.length-1);show();};
 $('#save-environment').onclick=()=>{try{stash();h.environment=normalizeEnvironment({items:rows},[h.housingCity,h.district,h.community].filter(Boolean).join(' '));save();$('#modal').close();toast('已保存周边资料，报告将区分线索与实际观察。');}catch(err){toast(err.message);}};
 };show();
}
