import {DIRECTIONS,EXTERNAL_TYPES,EXTERNAL_EFFECTS,EXTERNAL_FORMS,mapSearch,normalizeEnvironment,environmentAddress,environmentOpenings,environmentAssociation,bindEnvironmentLocation} from './residence.js?v=124593df2a03';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const opts=(map,val)=>Object.entries(map).map(([k,v])=>`<option value="${e(k)}" ${k===val?'selected':''}>${e(v)}</option>`).join('');
export function environmentRelationDiagrams(){
 const diagrams=[['道路轴线朝向开口','<path d="M44 94V30M76 94V30"/><path d="M60 88V40" stroke-dasharray="4 3"/><path d="m54 48 6-8 6 8"/>','在门窗处沿道路延长线核对，不能只看地图上很近。'],['房屋在外弯一侧','<path d="M17 89Q60 5 103 89M30 94Q60 32 90 94"/><path d="M60 53V36" stroke-dasharray="3 3"/><path d="m55 42 5-6 5 6"/>','先认清弯道内外侧，再看车灯、噪声是否确实进入这扇窗。'],['侧对或方向不明','<path d="M14 65H106M14 85H106"/><path d="M60 59V36" stroke-dasharray="2 5"/><path d="M92 69l8 6-8 6"/>','侧边经过不等于直冲；无法确认时保留“形势未核实”。']];
 return `<div class="environment-diagrams">${diagrams.map(([title,paths,note],i)=>`<figure><svg viewBox="0 0 120 108" role="img" aria-label="${title}关系示意" fill="none" stroke="currentColor" stroke-width="2"><rect x="43" y="8" width="34" height="20"/><path d="M52 28h16" stroke="#d5b671" stroke-width="5"/>${paths}</svg><figcaption><b>${i+1}. ${title}</b><span>${note}</span></figcaption></figure>`).join('')}</div><p class="hint">金色短线代表门窗。示意只帮助核对关系，不能代替现场确认。</p>`;
}
export function environmentStepError(row,screen){if(screen===0&&!row.locationChoice)return '请选择对应功能区；暂时不清楚可选“待关联功能区”。';if(screen===0&&row.method==='onsite'&&!String(row.position||'').trim())return '请填写现场观察位置。';if(screen===1&&!String(row.name||'').trim())return '请填写窗外地点或景物名称。';return '';}
export function editEnvironment(h,{modal,save,toast,initialDirection}){
 const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
 const blank=()=>({name:'',direction:initialDirection||'北',kind:'building',effect:'unknown',distance:'',layer:'',source:'',position:'',url:'',note:'',form:'unknown',formConfirmed:false,method:'onsite',observedAt:'',floorId:'',roomId:'',markerId:'',associationVersion:1,associationStatus:'pending',locationChoice:'',address:environmentAddress(h)});
 const rows=(h.environment?.items||[]).map(x=>{const relation=environmentAssociation(h,x);return {...blank(),...x,direction:x.direction||DIRECTIONS[Math.round((x.bearing||0)/45)%8],distance:x.distance??'',method:x.method||(x.effect&&x.effect!=='unknown'?'onsite':'map'),locationChoice:x.roomId?x.floorId+'/'+x.roomId:'pending',needsReview:relation.status==='stale'||!!x.needsReview,address:x.address??h.environment?.address??'',associationStatus:relation.status==='linked'?'linked':'pending',associationVersion:1};});
 let index=initialDirection?rows.findIndex(x=>x.direction===initialDirection):0;if(!rows.length||index<0){rows.push(blank());index=rows.length-1;}let screen=0;
 const stash=()=>{all('#modal [data-environment]').forEach(el=>rows[index][el.dataset.environment]=el.type==='checkbox'?el.checked:el.value);if(rows[index].method==='map'){rows[index].effect='unknown';rows[index].formConfirmed=false;}};
 const feedback=message=>{const el=$('#environment-feedback');if(el){el.hidden=false;el.textContent=message;el.scrollIntoView({block:'nearest'});}};
 const field=(label,body)=>`<label class="field"><span>${label}</span>${body}</label>`;
 const input=(key,placeholder='',type='text')=>`<input data-environment="${key}" aria-label="${placeholder}" type="${type}" value="${e(rows[index][key])}" placeholder="${placeholder}" maxlength="240">`;
 const select=(key,map)=>`<select data-environment="${key}">${opts(map,rows[index][key])}</select>`;
 const show=()=>{const x=rows[index],rooms=h.floors.flatMap(f=>f.rooms.map(r=>({value:f.id+'/'+r.id,name:f.name+' · '+r.name}))),openings=environmentOpenings(h,x.floorId,x.roomId),relation=environmentAssociation({...h,environment:{...h.environment,status:'recorded'}},x);let body='';
 if(screen===0)body=`<p class="hint">每条记录只对应所选功能区。无法确定时，先保存为待关联；不会推定影响全屋。</p><div class="environment-tabs">${rows.map((x,i)=>`<button data-env-index="${i}" class="${i===index?'selected':''}">${i+1}. ${e(x.name||'新记录')}</button>`).join('')}<button id="add-environment">＋ 添加</button></div>${field('对应功能区',`<select id="env-room" aria-label="对应功能区"><option value="">请选择功能区</option><option value="pending" ${x.locationChoice==='pending'?'selected':''}>待关联功能区（暂时不清楚）</option>${rooms.map(r=>`<option value="${e(r.value)}" ${r.value===x.locationChoice?'selected':''}>${e(r.name)}</option>`).join('')}${x.roomId&&!rooms.some(r=>r.value===x.locationChoice)?`<option value="${e(x.locationChoice)}" selected>原功能区已删除 · 请重新选择</option>`:''}</select>`)}${x.roomId?field('具体门窗（选填）',`<select id="env-opening" aria-label="对应门窗"><option value="">未选具体门窗，按功能区记录</option>${openings.map(m=>`<option value="${e(m.id)}" ${m.id===x.markerId?'selected':''}>${e(m.label)}</option>`).join('')}${x.markerId&&!openings.some(m=>m.id===x.markerId)?`<option value="${e(x.markerId)}" selected>原门窗已变化 · 请重选</option>`:''}</select><small>只列图中属于或邻近本区的门窗，请核对实际归属。</small>`):''}${field('观察位置',input('position','如：客厅南窗 / 入户门口'))}<div class="form-grid">${field('门窗外的方位',select('direction',Object.fromEntries(DIRECTIONS.map(x=>[x,x]))))}${field('资料来源方式',select('method',{onsite:'我到现场观察',map:'先从免费地图查找'}))}</div>${relation.status==='stale'?`<p class="environment-review-note">${e(relation.reason)}原记录与来源继续保留。</p><label class="check"><input id="env-recheck" type="checkbox">已回原位置核对，继续使用这条观察</label>`:''}<a class="text-link" href="${e(mapSearch(h))}" target="_blank" rel="noopener noreferrer">在高德查找楼栋 ↗</a><small>仅跳转地址查找；不发送八字或户型图。</small><button class="text-link" id="remove-environment">删除这条记录</button>`;
 if(screen===1)body=`<p class="hint">${e(x.position||'所选位置')} · ${e(x.direction)}侧。按实际看到的情况填写。</p>${field('地点或景物名称',input('name','如：南侧主路 / 对面3号楼'))}<div class="form-grid">${field('周边类型',select('kind',EXTERNAL_TYPES))}${field('距离（米，选填）',input('distance','不知道可留空','number'))}</div>${field('楼层与高低参照（选填）',input('layer','如：本宅12楼，对面约18层'))}${field('与门窗的形势关系',select('form',EXTERNAL_FORMS))}<details class="environment-relation-help"><summary>看三种关系示意</summary>${environmentRelationDiagrams()}</details>${x.method==='onsite'?`<label class="check"><input type="checkbox" data-environment="formConfirmed" ${x.formConfirmed?'checked':''}> 已在此门窗处核对形势与方向</label>`:'<p class="hint">地图可查道路、河流与楼栋位置；是否正对这扇窗，留待现场核实。</p>'}`;
 if(screen===2)body=`<p class="hint">${e(x.direction)} · ${e(x.name||'周边记录')}</p>${x.method==='onsite'?field('实际影响',select('effect',EXTERNAL_EFFECTS))+field('观察时间（选填）',input('observedAt','如：9月13日，上午10点')):'<p>这条记录作为地图线索保存，实际影响保持待核实。</p>'}${field('来源名称（选填）',input('source','如：本人窗边观察 / 高德地图'))}<details><summary>补充来源链接或说明（选填）</summary>${field('来源链接',input('url','https://…','url'))}${field('其他观察',input('note','如：关窗后仍能听见车流'))}</details>${x.needsReview?'<p class="environment-review-note">此条仍待重新核对，保存后保留来源，不产生房间调整结论。</p>':''}<p class="hint">结论仅对应记录时段，不推定全天情况。无需上传视频或照片。</p>`;
 modal('宅外补录 · '+['位置与方位','窗外形势','实际影响'][screen],`<div class="recognition-editor environment-editor" data-survey-screen="${screen}"><div class="survey-progress">${['1 位置','2 形势','3 影响'].map((v,i)=>`<span class="${i===screen?'active':''}">${v}</span>`).join('')}</div><p id="environment-feedback" class="environment-feedback" role="alert" hidden></p>${body}</div>`,`<button class="btn ghost" ${screen?'id="env-prev"':'data-close'}>${screen?'← 上一步':'取消'}</button><button class="btn primary" id="${screen===2?'save-environment':'env-next'}">${screen===2?'保存周边资料':'下一步 →'}</button>`,{className:'recognition-modal environment-modal'});
 $('#env-prev')?.addEventListener('click',()=>{stash();screen--;show();});
 $('#env-next')?.addEventListener('click',()=>{stash();const error=environmentStepError(rows[index],screen);if(error){feedback(error);return;}screen++;show();});
 all('#modal [data-env-index]').forEach(el=>el.onclick=()=>{stash();index=+el.dataset.envIndex;show();});
 $('#env-room')?.addEventListener('change',ev=>{stash();const row=rows[index],hadObservation=!!row.name&&row.effect!=='unknown',[fid,rid]=ev.target.value.split('/');row.locationChoice=ev.target.value;row.floorId=rid?fid:'';row.roomId=rid||'';row.markerId='';rows[index]=bindEnvironmentLocation(h,row);if(hadObservation)rows[index].needsReview=true;const r=h.floors.find(f=>f.id===fid)?.rooms.find(r=>r.id===rid);if(r&&!row.position)rows[index].position=r.name+'窗边';show();});
 $('#env-opening')?.addEventListener('change',ev=>{stash();try{const row=rows[index],changed=row.markerId!==ev.target.value;row.markerId=ev.target.value;rows[index]=bindEnvironmentLocation(h,row);if(changed&&row.name&&row.effect!=='unknown')rows[index].needsReview=true;show();}catch(err){feedback(err.message);}});
 $('#env-recheck')?.addEventListener('change',ev=>{if(!ev.target.checked)return;stash();try{const row=rows[index];if(row.roomId&&!rooms.some(r=>r.value===row.floorId+'/'+row.roomId))throw Error('原功能区已删除，请先重新选择。');rows[index]=bindEnvironmentLocation(h,row);show();}catch(err){ev.target.checked=false;feedback(err.message);}});
 $('[data-environment="method"]')?.addEventListener('change',()=>{stash();show();});
 $('#add-environment')?.addEventListener('click',()=>{stash();if(rows.length>=24){feedback('最多保存 24 条周边记录。');return;}rows.push(blank());index=rows.length-1;show();});
 $('#remove-environment')?.addEventListener('click',()=>{rows.splice(index,1);if(!rows.length){rows.push(blank());screen=2;}index=Math.min(index,rows.length-1);show();});
 $('#save-environment')?.addEventListener('click',async()=>{const previous=h.environment;try{stash();for(const row of rows.filter(x=>x.name.trim())){const error=environmentStepError(row,0);if(error)throw Error(error);}const result=normalizeEnvironment({items:rows},environmentAddress(h),h);h.environment=result;await save();$('#modal').close();toast('已保存周边资料，报告已更新。');}catch(err){h.environment=previous;feedback(err.message);}});
 };show();
}
