import {DIRECTIONS,EXTERNAL_TYPES,EXTERNAL_EFFECTS,EXTERNAL_FORMS,mapSearch,normalizeEnvironment} from './residence.js?v=52d9643d21e1';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const opts=(map,val)=>Object.entries(map).map(([k,v])=>`<option value="${k}" ${k===val?'selected':''}>${e(v)}</option>`).join('');
export function editEnvironment(h,{modal,save,toast,initialDirection}){
 const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
 const blank=()=>({name:'',direction:initialDirection||'北',kind:'building',effect:'unknown',distance:'',source:'',position:'',url:'',note:'',form:'unknown',formConfirmed:false,method:'onsite',observedAt:'',floorId:'',roomId:''});
 const rows=(h.environment?.items||[]).map(x=>({...blank(),...x,direction:x.direction||DIRECTIONS[Math.round((x.bearing||0)/45)%8],distance:x.distance??'',method:x.method||(x.effect&&x.effect!=='unknown'?'onsite':'map'),...(h.environment?.status==='stale'?{effect:'unknown',formConfirmed:false}:{})}));
 let index=initialDirection?rows.findIndex(x=>x.direction===initialDirection):0;if(!rows.length||index<0){rows.push(blank());index=rows.length-1;}let screen=0;
 const stash=()=>{all('[data-environment]').forEach(el=>rows[index][el.dataset.environment]=el.type==='checkbox'?el.checked:el.value);if(rows[index].method==='map'){rows[index].effect='unknown';rows[index].formConfirmed=false;}};
 const field=(label,body)=>`<label class="field"><span>${label}</span>${body}</label>`;
 const input=(key,placeholder='',type='text')=>`<input data-environment="${key}" aria-label="${placeholder}" type="${type}" value="${e(rows[index][key])}" placeholder="${placeholder}" maxlength="240">`;
 const select=(key,map)=>`<select data-environment="${key}">${opts(map,rows[index][key])}</select>`;
 const show=()=>{const x=rows[index],rooms=h.floors.flatMap(f=>f.rooms.map(r=>({value:f.id+'/'+r.id,name:f.name+' · '+r.name})));let body='';
 if(screen===0)body=`<p class="hint">先选一扇常用窗或入户门，站在同一位置逐项记录。${h.environment?.status==='stale'?'地址已修改，旧记录需重新核对。':''}</p><div class="environment-tabs">${rows.map((x,i)=>`<button data-env-index="${i}" class="${i===index?'selected':''}">${i+1}. ${e(x.name||'新记录')}</button>`).join('')}<button id="add-environment">＋ 添加</button></div>${field('对应功能区',`<select id="env-room"><option value="">手动填写观察位置</option>${rooms.map(r=>`<option value="${e(r.value)}" ${r.value===x.floorId+'/'+x.roomId?'selected':''}>${e(r.name)}</option>`).join('')}</select>`)}${field('观察位置',input('position','如：客厅南窗 / 入户门口'))}<div class="form-grid">${field('门窗外的方位',select('direction',Object.fromEntries(DIRECTIONS.map(x=>[x,x]))))}${field('资料来源方式',select('method',{onsite:'我到现场观察',map:'先从免费地图查找'}))}</div><a class="text-link" href="${e(mapSearch(h))}" target="_blank" rel="noopener noreferrer">在高德查找楼栋 ↗</a><small>仅跳转地址查找；不发送八字或户型图。</small><button class="text-link" id="remove-environment">删除这条记录</button>`;
 if(screen===1)body=`<p class="hint">${e(x.position||'所选位置')} · ${e(x.direction)}侧。按实际看到的情况填写。</p>${field('地点或景物名称',input('name','如：南侧主路 / 对面3号楼'))}<div class="form-grid">${field('周边类型',select('kind',EXTERNAL_TYPES))}${field('距离（米，选填）',input('distance','不知道可留空','number'))}</div>${field('与门窗的形势关系',select('form',EXTERNAL_FORMS))}${x.method==='onsite'?`<label class="check"><input type="checkbox" data-environment="formConfirmed" ${x.formConfirmed?'checked':''}> 已在此门窗处核对形势与方向</label>`:'<p class="hint">地图可查道路、河流与楼栋位置；是否正对这扇窗，留待现场核实。</p>'}`;
 if(screen===2)body=`<p class="hint">${e(x.direction)} · ${e(x.name||'周边记录')}</p>${x.method==='onsite'?field('实际影响',select('effect',EXTERNAL_EFFECTS))+field('观察时间（选填）',input('observedAt','如：9月13日，上午10点')):'<p>这条记录作为地图线索保存，实际影响保持待核实。</p>'}${field('来源名称（选填）',input('source','如：本人窗边观察 / 高德地图'))}<details><summary>补充来源链接或说明（选填）</summary>${field('来源链接',input('url','https://…','url'))}${field('其他观察',input('note','如：关窗后仍能听见车流'))}</details><p class="hint">保存后可继续补录另一扇窗；不要求上传视频或照片。</p>`;
 modal('宅外补录 · '+['位置与方位','窗外形势','实际影响'][screen],`<div class="environment-editor" data-survey-screen="${screen}"><div class="survey-progress">${['1 位置','2 形势','3 影响'].map((v,i)=>`<span class="${i===screen?'active':''}">${v}</span>`).join('')}</div>${body}</div>`,`<button class="btn ghost" ${screen?'id="env-prev"':'data-close'}>${screen?'← 上一步':'取消'}</button><button class="btn primary" id="${screen===2?'save-environment':'env-next'}">${screen===2?'保存周边资料':'下一步 →'}</button>`);
 $('#env-prev')?.addEventListener('click',()=>{stash();screen--;show();});
 $('#env-next')?.addEventListener('click',()=>{stash();if(screen===0&&rows[index].method==='onsite'&&!rows[index].position.trim()){toast('请填写观察位置。');return;}if(screen===1&&!rows[index].name.trim()){toast('请填写窗外地点或景物名称。');return;}screen++;show();});
 all('[data-env-index]').forEach(el=>el.onclick=()=>{stash();index=+el.dataset.envIndex;show();});
 $('#env-room')?.addEventListener('change',ev=>{stash();const [fid,rid]=ev.target.value.split('/');rows[index].floorId=fid||'';rows[index].roomId=rid||'';const r=h.floors.find(f=>f.id===fid)?.rooms.find(r=>r.id===rid);if(r)rows[index].position=r.name+'窗边';show();});
 $('#add-environment')?.addEventListener('click',()=>{stash();if(rows.length>=24){toast('最多保存 24 条周边记录。');return;}rows.push(blank());index=rows.length-1;show();});
 $('#remove-environment')?.addEventListener('click',()=>{rows.splice(index,1);if(!rows.length){rows.push(blank());screen=2;}index=Math.min(index,rows.length-1);show();});
 $('#save-environment')?.addEventListener('click',async()=>{try{stash();const result=normalizeEnvironment({items:rows},[h.housingCity,h.district,h.community].filter(Boolean).join(' '));h.environment=result;await save();$('#modal').close();toast('已保存周边资料，报告已更新。');}catch(err){toast(err.message);}});
 };show();
}
