import {ROLES,roleOf} from './residence.js?v=82168a3e723a';
import {ROOMS,TIERS,GOALS} from './core.js?v=82168a3e723a';
import {CATALOG} from './catalog.js?v=82168a3e723a';
import {symbol} from './plan-symbols.js?v=82168a3e723a';
import {validPolygon,insideRoom} from './geometry.js?v=82168a3e723a';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const SCREENS=[['A','户主八字'],['A','改造预算'],['A','改造范围'],['B','住宅基本资料'],['B','上传户型图'],['B','勾画边界红线'],['B','填写最长尺寸'],['B','确认八个方位'],['C','分割功能区'],['D','标记软装位置'],['E','核对并生成']];
const field=(name,body)=>`<label class="field"><span>${name}</span>${body}</label>`;
const inp=(key,value,extra='')=>`<input data-field="${key}" value="${e(value)}" ${extra}>`;
const opts=(map,val)=>Object.entries(map).map(([k,v])=>`<option value="${k}" ${String(val)===k?'selected':''}>${e(v)}</option>`).join('');
export {stageError,dimensionValid,regionWithin} from './intake-validation.js?v=82168a3e723a';
export function intake(h,s,fi,{canvas,floorTabs,selection,tool,sketch,services={},reportEdit=false,buyerBirth=false}){const b=h.birth,f=h.floors[fi],r=f?.rooms.find(x=>x.id===selection);let body='';
 const drawing=extra=>`${floorTabs(h.floors,fi,true)}<div class="intake-drawing ${s===5?'boundary-mode':''}"><div class="drawing-viewport" data-aspect="${f.width/f.height}"><div class="drawing-sheet">${canvas(f,{editable:[5,6,8,9].includes(s),show:s>=8})}${extra||''}</div><div class="drawing-zoom"><button data-action="toggle-drawing" aria-label="展开或收起画图工作区">⛶</button><button data-zoom="out" aria-label="缩小图纸">−</button><button data-zoom="reset" aria-label="复位图纸">⌖</button><button data-zoom="in" aria-label="放大图纸">＋</button></div></div></div>`;
 const strokeTools=kind=>`<div class="compact-tools"><button data-tool="select">移动</button><button data-tool="${kind}">重新勾线</button><button data-action="undo-point" ${sketch.length?'':'disabled'}>撤回</button><button data-action="close-polygon" ${sketch.length>=3?'':'disabled'}>闭合</button></div>`;
 if(s===0){const parts=(b.date||'').split('-'),year=b.year||parts[0]||'',month=b.month||parts[1]||'',day=b.day||parts[2]||'',days=year&&month?new Date(Number(year),Number(month),0).getDate():31;const pick=(key,val,max,min=1)=>`<select data-date-part="${key}" aria-label="出生${{year:'年',month:'月',day:'日'}[key]}" ${!b.consent||key==='month'&&!year||key==='day'&&(!year||!month)?'disabled':''}><option value="">${{year:'年',month:'月',day:'日'}[key]}</option>${Array.from({length:max-min+1},(_,i)=>key==='year'?max-i:min+i).map(v=>`<option value="${v}" ${Number(val)===v?'selected':''}>${v}${{year:'年',month:'月',day:'日'}[key]}</option>`).join('')}</select>`;body=`<p class="birth-caption">先了解人，再看宅 · 公历 / 北京时间</p><label class="check"><input id="birth-consent-inline" type="checkbox" ${b.consent?'checked':''}> 同意在本机处理出生资料</label><div class="birth-date-row">${pick('year',year,new Date().getFullYear(),1901)}${pick('month',month,12)}${pick('day',day,days)}</div><div class="form-grid">${field('出生时间',`<input type="time" data-birth="time" value="${e(b.time)}" ${!b.consent||b.unknown?'disabled':''}>`)}${field('出生城市',`<input data-birth="city" value="${e(b.city)}" placeholder="如：杭州" maxlength="30" ${!b.consent?'disabled':''}>`)}${field('家庭身份',`<select data-field="householdRole">${opts(Object.fromEntries(Object.entries(ROLES).map(([k,v])=>[k,v.name])),h.householdRole||'')}</select>`)}${field('性别',`<select data-birth="sex" ${!b.consent?'disabled':''}>${opts({'':'请选择',男:'男',女:'女'},b.sex||'')}</select>`)}</div><label class="check"><input data-birth="unknown" type="checkbox" ${b.unknown?'checked':''} ${!b.consent?'disabled':''}> 时辰不详</label><button class="btn outline" data-action="preview-birth" ${!b.consent?'disabled':''}>查看四柱</button><small>喜用参考将自动推导；${buyerBirth?'时辰不详可先用三柱；个人方位待时辰核对后再定。':'不填写也可先看住宅。'}</small>`;}
 if(s===1)body=`${field('可接受的改造预算（元）',inp('budget',h.budget,'type="number" min="0" max="10000000"'))}<p class="hint">优先利用现有家具。预算为 0 元，也可以选择整理和重新摆放。</p>`;
 if(s===2)body=`${field('房子的类型',`<select data-field="type">${opts({apartment:'商品房',self:'自建房',villa:'别墅 / 多层'},h.type)}</select>`)}<div class="finish-options">${[['shell','毛坯'],['furnished','精装']].map(([k,v])=>`<button data-finish="${k}" class="${h.finish===k?'selected':''}">${v}</button>`).join('')}</div><div class="compact-tiers">${Object.entries(TIERS).map(([k,t])=>`<button data-tier="${k}" class="${h.tier===k?'selected':''}"><b>${t.name}</b><span>${e(t.text)}</span></button>`).join('')}</div>`;
 if(s===3)body=`<div class="form-grid">${field('城市',inp('housingCity',h.housingCity,'placeholder="如：杭州" maxlength="30"'))}${field('区域',inp('district',h.district,'placeholder="如：西湖区" maxlength="30"'))}${field('小区 / 自建地名',inp('community',h.community,'maxlength="60"'))}${field('总面积（㎡）',inp('area',h.area,'type="number" min="1" max="5000"'))}${field('几房',inp('bedrooms',h.bedrooms,'type="number" min="0" max="50"'))}${field('几厅',inp('livingrooms',h.livingrooms,'type="number" min="0" max="20"'))}${field('常住人数',inp('residents',h.residents,'type="number" min="1" max="30"'))}${field('所在楼层（选填）',inp('buildingFloor',h.buildingFloor,'type="number" min="-5" max="200" placeholder="如：12"'))}${field('楼栋总层数（选填）',inp('buildingTotalFloors',h.buildingTotalFloors,'type="number" min="1" max="200" placeholder="如：18"'))}${field('宅档名称（选填）',inp('name',h.name,'maxlength="40"'))}</div><button class="text-link" data-action="map-environment">宅外周边 · 免费查找与录入 →</button><small>${e(h.environment?.items?.length?`已记录 ${h.environment.items.length} 项周边情况${h.environment.status==='stale'?' · 地址已改，请重核':''}`:'地图查找 + 窗边观察，不接入付费地图接口')}</small>`;
 if(s===4)body=`<div class="upload-zone" id="drop-zone"><h3>选择清楚的户型图</h3><label class="btn primary file-label">上传户型图<input id="file-input" type="file" accept="image/png,image/jpeg,image/webp" multiple></label><p>每张不超过 10 MB · 多层住宅可多选</p><small>自动识图适合黑白二维线稿；彩色效果图可手动勾画。</small></div><div class="compact-files">${h.floors.map((x,i)=>`<span>${e(x.name)} <button data-recognition-floor="${i}">自动识图${x.recognition?.candidates?.length?` · ${x.recognition.candidates.length} 区`:""}</button><button data-remove-floor="${i}" aria-label="删除${e(x.name)}">×</button></span>`).join('')}</div><button class="text-link" data-action="sample-upload">用示例户型体验 →</button>`;
 if(s===4&&services.vision)body+=`<label class="check"><input id="auto-furniture-consent" type="checkbox" ${h.furnitureConsent?'checked':''}> 自动识别图中家具（同意将户型图发送给识别服务）</label>`;
 if(s===5)body=`<p class="boundary-instruction">顶天顶地封死的为边界红线。<strong>半封阳台请不要标记红线，不作为布局纳入。</strong></p>${drawing()}${strokeTools('boundary')}<button class="text-link" data-action="recognition-dialog">自动识图 · 核对边界与房间 →</button><p class="hint">沿外墙逐点勾画，至少 3 点后闭合。${f.boundary?'已保存红线，可重新勾画。':`已选 ${sketch.length} 个点。`}</p>`;
 if(s===6)body=`${drawing(`<span class="measure-guide vertical" style="top:${f.bounds.y*100}%;height:${f.bounds.h*100}%;bottom:auto">↕ 纵向最长边</span><span class="measure-guide horizontal" style="left:${f.bounds.x*100}%;width:${f.bounds.w*100}%;right:auto">↔ 横向最长边</span>`)}<div class="form-grid">${field('横向最长单边（米）',`<input data-extent="width" value="${e(f.extents?.width||'')}" placeholder="米数或未知">`)}${field('纵向最长单边（米）',`<input data-extent="height" value="${e(f.extents?.height||'')}" placeholder="米数或未知">`)}</div><p class="hint">填写图纸标示或实测值。辅助线表示横纵方向，不能用总面积反推精确尺寸。</p>`;
 if(s===6)body+=`<label class="check"><input id="extent-confirm" type="checkbox" ${f.extents?.confirmed?'checked':''}> 两条长度已核对实测或可靠尺寸图</label>`;
 if(s===7)body=`${drawing()}<p class="hint">选择“图纸上方”朝向，八方位会一起转动。</p><div class="eight-picker">${['北','东北','东','东南','南','西南','西','西北'].map((x,i)=>`<button data-north="${(360-i*45)%360}" class="${f.north===(360-i*45)%360?'active':''}">${x}</button>`).join('')}</div><label class="check"><input id="direction-confirm" type="checkbox" ${f.directionConfirmed?'checked':''}> 已核对这一层的八方位</label>`;
 if(s===8)body=`<div class="compact-tools"><button data-action="add-room">＋ 矩形</button><button data-tool="polygon">勾画功能区</button><button data-tool="select">移动 / 缩放</button></div>${drawing()}${r?`<div class="inline-room" aria-label="功能区编辑"><input data-room="name" aria-label="功能区名称" value="${e(r.name)}" maxlength="18"><select data-room="type" aria-label="功能区用途">${opts(ROOMS,r.type)}</select><input data-room="width" aria-label="功能区宽度" value="${e(r.measurements?.width||'')}" placeholder="宽：米 / 未知"><input data-room="depth" aria-label="功能区深度" value="${e(r.measurements?.depth||'')}" placeholder="长：米 / 未知"><button data-action="room-done">完成</button><button data-action="delete-object">删除</button></div>`:''}${tool==='polygon'?strokeTools('polygon'):`<p class="hint">${f.rooms.length} 个功能区 · 点选下方名称编辑、填尺寸；拖动四角缩放。</p>`}<div class="saved-objects">${f.rooms.map(x=>`<button data-review-room="${x.id}">${e(x.name)}</button>`).join('')}</div><div class="compact-tools"><button data-action="reference-dimensions">未知尺寸 / 查找参考</button><button data-action="recognition-dialog">自动识图 · 预览与采用</button></div>`;
 if(s===9)body=`<select id="marker-tool" aria-label="选择软装和设施"><option value="">添加家具 / 设施（无需尺寸）</option>${[...new Set(Object.values(CATALOG).map(x=>x.group))].map(g=>`<optgroup label="${e(g)}">${Object.entries(CATALOG).filter(([,x])=>x.group===g).map(([k,x])=>`<option value="${k}">${e(x.name)}</option>`).join('')}</optgroup>`).join('')}</select>${drawing()}<p class="hint">选择后出现在左上角，拖至实际位置。门窗、家具都请标在红线范围内。</p>${selection?`<div class="compact-tools furniture-controls"><span>${e(CATALOG[f.markers.find(m=>m.id===selection)?.type]?.name||'所选区域')}</span><input id="symbol-scale" type="range" min="0.5" max="3" step="0.1" value="${f.markers.find(m=>m.id===selection)?.uiScale||1}" aria-label="图标大小"><button data-symbol-size="-0.1" aria-label="缩小家具图标">−</button><button data-symbol-size="0.1" aria-label="放大家具图标">＋</button><label class="rotation-control">旋转 <input id="symbol-rotation" type="range" min="0" max="345" step="15" value="${f.markers.find(m=>m.id===selection)?.rotation||0}" aria-label="家具旋转角度"><output id="rotation-value">${f.markers.find(m=>m.id===selection)?.rotation||0}°</output></label><button data-symbol-rotate="90" aria-label="家具旋转90度">↻ 90°</button><button data-action="marker-done">完成</button><button data-action="delete-object">删除</button></div>`:''}<div class="saved-objects">${f.markers.map(m=>`<button data-review-marker="${m.id}" aria-label="编辑${e(CATALOG[m.type]?.name)}">${symbol(m.type)}</button>`).join('')}</div><button class="text-link" data-action="recognize-furniture">识别底图中的家具 →</button>`;
 if(s===10)body=`<div class="summary-facts"><b>${e(h.name||h.community)}</b><span>${e(h.housingCity)} ${e(h.district)} · ${e(h.community)}</span><span>${e(h.area)}㎡ · ${e(h.bedrooms)}房${e(h.livingrooms)}厅 · ${e(h.budget)}元 · ${TIERS[h.tier].name}${h.buildingFloor?` · ${e(h.buildingFloor)} / ${e(h.buildingTotalFloors||'未知')} 楼`:""}</span><span>${b.enabled?`${e(b.date)} ${b.unknown?'时辰不详':e(b.time)} · ${e(b.city)}`:'未填写出生资料'} · ${e(roleOf(h).name)}</span></div>${floorTabs(h.floors,fi,true)}<div class="drawing-viewport summary-viewport" data-aspect="${f.width/f.height}"><div class="drawing-sheet">${canvas(f,{show:true})}</div></div><div class="compact-tools"><button data-action="toggle-drawing">⛶ 展开图纸</button><button data-zoom="out" aria-label="缩小图纸">−</button><button data-zoom="reset">复位</button><button data-zoom="in" aria-label="放大图纸">＋</button><span>${f.rooms.length} 区 / ${f.markers.length} 个物件</span><button data-action="summary-details">全部资料</button></div><label class="check"><input id="summary-confirm" type="checkbox" ${h.summaryConfirmed?'checked':''}> 已核对全部楼层、红线、方位和资料</label>`;
 return `<section class="workspace intake-workspace ${s>=5?'drawing-step':''}"><div class="intake-heading"><span>${buyerBirth?'准备买房 / 户主八字':`${SCREENS[s][0]} / ${SCREENS[s][1]}`}</span>${s>=5?'<button class="text-link drawing-size-toggle" data-action="toggle-drawing">⛶ 展开 / 收起</button>':''}${!reportEdit&&!buyerBirth?'<button class="text-link" data-action="save-draft">保存草稿</button>':''}</div>${reportEdit?`<div class="report-edit-caption"><span>保存后直接返回原报告</span><select id="report-edit-section" aria-label="修改其他资料">${SCREENS.slice(0,10).map((x,i)=>`<option value="${i}" ${i===s?'selected':''}>${x[1]}</option>`).join('')}</select></div>`:buyerBirth?'':`<div class="intake-progress" aria-label="资料进度">${['A','B','C','D','E'].map((x,i)=>`<span class="${x===SCREENS[s][0]?'active':''}">${x} ${['户主','住宅','分区','软装','确认'][i]}</span>`).join('')}</div>`}<div class="intake-panel" id="wizard-content">${body}</div><div class="wizard-bottom"><button class="btn ghost" data-action="${buyerBirth?'buyer-prev':'prev'}">${reportEdit?'取消修改':'← 返回上一级'}</button><small>${reportEdit?'':buyerBirth?'1 / 2':`${s+1} / ${SCREENS.length}`}</small><button class="btn primary" data-action="${buyerBirth?'buyer-next':'next'}">${reportEdit?'保存并返回报告':s===10?'确认生成':'继续 →'}</button></div></section>`;
}
