import {TIERS,GOALS} from './core.js?v=52d9643d21e1';
import {orient,relation,lifeGua} from './deep.js?v=52d9643d21e1';
import {roomAnchor,insideRoom} from './geometry.js?v=52d9643d21e1';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ELEMENT={北:'水',东北:'土',东:'木',东南:'木',南:'火',西南:'土',西:'金',西北:'金'},GUA={北:'坎',东北:'艮',东:'震',东南:'巽',南:'离',西南:'坤',西:'兑',西北:'乾'};
const TERMS={focus:'形峦 · 动静分区',sight:'门与床 · 先看视线',concave:'形峦 · 因形布置'};
const COPY={
 focus:{title:'把办公留在固定位置，别让工作占满全屋',why:'形峦先分动静。图中没有独立书房，经常在家办公，就要让专注和休息各有归处；桌面反复搬动、饭桌兼作工位，都会增加日常切换的负担。',action:'先腾出一张能长期保留的桌面，把常用资料集中放在手边。桌椅拉开后，给家人留下正常经过的位置。无需在家办公，这项就不必改。',boost:'把工作用品收在这一处，结束后关闭工作灯，让休息时间有明确的开始。'},
 sight:{title:'先看门口能否见床，再决定床位怎么改',why:'图中的门位与卧室接近。安床先看房门：要解决的是开门后的暴露与打扰，不能只看两点距离。',action:'站在门口打开门。能直接见床，先调整未锁定床位的朝向；床不能动，就在视线经过处试放可移动遮挡。门后有完整墙体、看不见床，就保留原位。',boost:'遮挡试放后再开一次门：床位不直接暴露，门能开足，家人进出不必绕行，才算调整到位。'},
 concave:{title:'凹处做收纳，把完整地面留给活动',why:'形峦先看实形。这个房间有内凹，家具要顺着真实墙线安排。把凹处和开阔处当成一个大矩形来摆，容易堵住转角，也会浪费连续可用的地面。',action:'先量凹处的净宽与深度，再放尺寸合适的收纳柜；柜门朝向便于取物的一侧。主要活动区留在开阔处，别用装饰把红线外的空白当作室内。',boost:'先用现有收纳试摆，能站稳取物、柜门开足，再购买新柜子。优先解决转角通行，不急着添摆件。'},
 entry:{title:'补上入户门',action:'标出真正的入户门，再从门口看客厅与卧室。入口位置明确后，才能决定玄关是否需要遮挡。'},
 window:{title:'补上窗位',action:'标出可以开启的窗，并在常用时段看光线。卧室再定遮光帘，书桌再定灯位；不要只凭房间朝向购买。'},
 dimensions:{title:'移动或购买前，先量这三处',action:'量家具最大外形、拟摆位置的净空，以及门窗开足所占的范围。三项对得上，再搬动或下单。'},
 outside:{title:'到现场看窗外',action:'站在主要窗边，查看遮挡、噪声和道路。户型图没有这些条件，本次不判断宅外形势。'}
};
export function readingItem(h,x){const c={...COPY[x.caseKey]},f=h.floors.find(f=>f.id===x.floorId),r=f?.rooms.find(r=>r.id===x.roomId);
 if(x.caseKey==='sight'&&r){const marks=f.markers.filter(m=>insideRoom(m,r)),bed=marks.some(m=>m.type==='bed')||r.type==='bedroom';if(!bed){c.term='门与座 · 先看视线';c.title='先看开门的视线，再调整常坐的位置';c.why=`${r.name}的主要家具与一处门位接近同一直线。座位应避开频繁进出的直接干扰，重点是实际开门后看见什么。`;c.action='开门后若直接面对座位，先转动或移动未锁定家具，让视线错开；中间有墙挡住，就保留原位。调整后把门开足，检查通道是否被占。';c.boost='在新位置完整使用一次，起身、取物、家人经过都顺畅，再固定摆法。';}}
 if(x.caseKey==='focus'&&h.tier==='medium')c.action='保留墙体，可将低频使用区改为工作区，腾出一张固定桌面，用台灯和集中收纳形成工作角。桌椅拉开后留出通道；不常在家办公，就不必另设工位。';
 if(x.caseKey==='focus'&&h.tier==='small')c.action='不动墙和管线，把低频使用的一角改成固定工作区。先把桌、椅、资料收在同一处，试用后再确定分区；不在家办公就不必改。';
 if(x.caseKey==='focus'&&h.tier==='large')c.action='先用桌椅试出办公区真正需要的面积。长期使用确实受干扰，再讨论隔断；施工前确认承重与采光。';
 if(x.caseKey==='concave'&&h.tier==='large')c.action+=' 凹处是否能改墙，先确认里面有没有柱体、管井。';
 if(x.locked&&x.kind==='attention')c.action='保留锁定区域和物件原位。'+(x.caseKey==='sight'?'开门直见床或常用座位时，只在不挡门、不占通道的位置增加可移动遮挡；有墙隔开就不改。':x.caseKey==='concave'?'只整理未锁定的小件，让凹处便于取放、转角便于经过；新增柜子前先量尺寸。':'只在未锁定、用途允许的位置整理工作桌面和收纳；没有合适位置就保留现状。');
 const room=r?`${f.name} · ${r.name}`:f?.name||'全屋';
 return {...x,...c,where:room,term:c.term||TERMS[x.caseKey]||'',why:c.why||'',boost:c.boost||({entry:'把入口处临时堆放的物品收进固定位置，先保持进出顺畅。',window:'先试现有窗帘和灯位，能解决刺眼或过亮，再决定要不要添置。',dimensions:'把购物清单分成必须购买与可以沿用两列，先从可以沿用的物品开始安排。',outside:'选平常工作和休息的时段各去看一次，记录真正影响日常的干扰。'})[x.caseKey]||''};
}
function retained(h){const out=[];for(const f of h.floors){const study=f.rooms.find(r=>r.type==='study'),bed=f.rooms.find(r=>r.type==='bedroom');if(study)out.push({title:`保留${study.name}的专注用途`,body:'工作与休息分开，日常更容易收拢注意力。把常用资料集中在这里，不再分散到卧室。'});if(bed)out.push({title:`保留${bed.name}的休息用途`,body:'床边少放临时杂物，夜间常用的物品放在伸手可及处，减少来回走动。'});if(out.length>=2)break;}return out;}
function personal(h,b,color){if(!b)return '<section class="personal-fit report-section"><h2>先看房子，再补个人适配</h2><p>补上出生日期、时间和城市，才能把住宅方位与户主八字放在一起看。</p><button class="text-link" data-action="report-birth">填写户主八字 →</button></section>';
 const places=h.floors.flatMap(f=>f.rooms.filter(r=>['bedroom','study','living'].includes(r.type)).map(r=>({f,r,d:orient(roomAnchor(r),f)})));
 const same=color.element?places.find(x=>ELEMENT[x.d]===color.element):null,chosen=same||places.find(x=>x.r.type==='bedroom')||places[0];let body='';
 if(chosen){const {f,r,d}=chosen,el=ELEMENT[d],loc=h.floors.length>1?f.name+'的'+r.name:r.name;body=el?`${loc}在${d}，后天八卦属${GUA[d]}${el}。`:`${loc}靠近中部，先安排实际用途。`;if(el){const rel=relation(b.dayMaster.element,el),meaning={同气:'与日主同气，也就是五行同类',生我:'生扶日主，在八字里取印星承托之意',我生:'由日主所生，在八字里取食伤泄秀、表达输出之意',我克:'被日主所克，在八字里取财星管理资源之意',克我:'克制日主，在八字里取官杀规范约束之意'};body+=`${b.dayMaster.stem}${b.dayMaster.element}与这一方的关系是：${meaning[rel]}。`;}
 body+=h.favorable&&h.favorableSource?(same?`你填写的喜用为${h.favorable}，这一处与喜用同类，配色就从这里入手。把${color.style.names}用在这里的窗帘或织物上，主家具先保留。`:`你填写的喜用为${h.favorable}。本轮按${color.style.names}安排软装，不因单一方位更换房间用途。`):'尚未确定喜用，不能据这层生克决定搬房；先把休息、采光与通行安排好。';}
 const gua=lifeGua(b.chartYear,h.birth.sex),pillars=['year','month','day','hour'].map(k=>b.pillars[k]?b.pillars[k].stem+b.pillars[k].branch:'时辰不详').join(' · ');
 const issue=b.unknown?'时辰不详，个人适配先保留到日期层。':b.boundaries?.length?'出生时间接近换日或节气分界，先核对准确时间。':!b.solar?.lonSource?.startsWith('city:')?'出生城市未匹配，请更正城市后再看个人适配。':'';
 return `<section class="personal-fit report-section"><span class="eyebrow">合其人</span><h2>${e(b.dayMaster.stem+b.dayMaster.element)}日主，${h.favorable&&h.favorableSource?`喜${e(h.favorable)}先调织物配色`:color.element?'配色先取扶抑参考':'先保留现有房间用途'}</h2><p>${e(issue||body||'先确定各个房间的用途，再按喜用安排局部颜色。')}</p><details class="report-reference"><summary>查看四柱与命卦</summary><p>${e(pillars)}${gua?`；八宅命卦为${e(gua.gua)}命。`:''}</p><p>命卦用于八宅方位，喜用用于八字取舍，两者分别阅读。</p><button class="text-link" data-action="report-birth">修改出生资料 →</button></details></section>`;
}
function colors(h,b,color){let basis,title;if(h.favorable&&h.favorableSource){title=`已知喜用${h.favorable}，用在局部就够了`;basis=`按你提供的喜用，选择${color.style.names}。大面积保留原有中性色，先更换一两件织物，避免为了配色重买整套家具。`;}else if(color.element){title=`${color.element}行配色，作为扶抑参考`;basis=`按扶抑思路，${b.dayMaster.stem}${b.dayMaster.element}日主${b.fiveElements.dayMasterStrength.label==='偏弱'?`偏弱，取${color.element}生${b.dayMaster.element}，借印星生扶之意`:`偏强，取${b.dayMaster.element}生${color.element}，借食伤泄秀之意`}。这组用${color.style.names}，先在抱枕或桌布上试色；它是扶抑配色参考，尚未定为喜用。`;}else{title='喜用未定，先统一现有颜色';basis='保留大件家具的颜色，从现有木色或织物中选一个主调；零散装饰减到同一组，空间就更整齐。';}
 const style=({木:'自然原木',火:'暖调现代',土:'质朴棉麻',金:'简约雅致',水:'沉静现代'})[color.element]||'温和简约';
 return `<section class="palette-card report-section"><span class="eyebrow">颜色与风格</span><h2>${e(title)}</h2><p>${e(basis)}</p><div class="swatches">${color.style.colors.map(c=>`<div style="background:${c}"></div>`).join('')}</div><p><b>${e(style)}</b>：选${e(color.style.material)}。先看白天和开灯后的颜色，再确定窗帘、抱枕与地毯是否协调。</p></section>`;
}
export function renderReading(h,b,items,color,selected,saved){const read=items.map(x=>readingItem(h,x)),attention=read.filter(x=>x.kind==='attention'),missing=read.filter(x=>x.kind==='unknown'),keep=retained(h);const groups=[];
 for(const x of attention){const key=x.caseKey+'-'+x.floorId+'-'+x.roomId;const g=groups.find(g=>g.key===key);if(g)g.ids.push(x.id);else groups.push({...x,key,ids:[x.id]});}
 const heading=({focus:'固定办公桌面，把工作和休息分开',sight:'先检查开门视线，再调床或座位',concave:'凹处安排收纳，转角留给通行'})[groups[0]?.caseKey]||(keep.length?'保留现有分区，先把门窗和尺寸补清':'先明确房间用途，再安排家具');
 return `<section class="consultation-overview report-section"><span class="eyebrow">观宅 · 总论</span><h2>${e(heading)}</h2><p>${keep.length?keep.map(x=>e(x.title)).join('，')+'。':'先标清休息与日常活动的位置。'}${groups.length?`本次重点处理${groups.map(x=>x.where==='全屋'?x.title:x.where).slice(0,3).map(e).join('、')}。`:'门窗与实测长度补齐后，再定家具的位置。'}</p><p class="reading-budget">${e(TIERS[h.tier].name)} · 预算上限 ${e(h.budget)} 元${h.keep?` · 保留：${e(h.keep)}`:''}</p></section>${personal(h,b,color)}${keep.length?`<section class="report-section retain-reading"><h2>这些安排，先保留</h2>${keep.map(x=>`<p><b>${e(x.title)}。</b>${e(x.body)}</p>`).join('')}</section>`:''}<section class="improvement-picker report-section"><h2>你最在意哪几项？</h2><p>最多选三项加强，其他问题也会处理。</p><div class="goal-grid">${Object.entries(GOALS).map(([k,v])=>`<button class="goal ${selected.includes(k)?'selected':''}" data-improve-goal="${k}" aria-pressed="${selected.includes(k)}">${v}</button>`).join('')}</div><button class="btn primary" data-action="improve-all">${saved?'更新重点':'加强所选方向'}</button></section><section class="improvement-results" data-enhanced="${!!saved}"><div class="reading-cases">${groups.map(x=>{const boosted=!!saved&&x.tags.some(g=>saved.goals.includes(g));return `<article class="reading-case report-section" data-finding-room="${e(x.roomId||'')}" data-remedy="${e(x.ids[0])}">${x.ids.slice(1).map(id=>`<span data-remedy="${e(id)}" hidden></span>`).join('')}<span class="eyebrow">${e(x.where)} · ${e(x.term)}${boosted?' · 重点加强':''}</span><h2>${e(x.title)}</h2><p>${e(x.why)}</p><p class="reading-action"><b>先这样做：</b>${e(x.action)}</p>${boosted?`<p class="reading-boost"><b>再加强一步：</b>${e(x.boost)}</p>`:''}${x.roomId?`<button class="text-link" data-locate="${e(x.roomId)}" data-locate-floor="${e(x.floorId)}">查看图中位置 ↗</button>`:''}</article>`;}).join('')}</div>${colors(h,b,color)}${missing.length?`<section class="report-section missing-reading"><h2>动手前，补齐这几件事</h2>${missing.map(x=>`<p data-remedy="${e(x.id)}"><b>${h.floors.length>1&&x.floorId?e(x.where)+' · ':''}${e(x.title)}。</b>${e(x.action)}${saved&&x.tags.some(g=>saved.goals.includes(g))?`<br><span class="reading-boost">重点加强：${e(x.boost)}</span>`:''}</p>`).join('')}</section>`:''}</section>`;
}
