import {renderPalaces,PALACES} from './direction-reading.js?v=82168a3e723a';
import {GOALS,TIERS} from './core.js?v=82168a3e723a';
import {orient} from './deep.js?v=82168a3e723a';
import {roomAnchor} from './geometry.js?v=82168a3e723a';
import {favorableReference,paletteGroups} from './favorable.js?v=82168a3e723a';
import {missingInputs,directionItems,yearAdvice,GUA} from './report-data.js?v=82168a3e723a';
import {readingItem} from './report-copy.js?v=82168a3e723a';
import {roleOf,roleNote,sleepingDirection,externalFindings,boundaryNotches} from './residence.js?v=82168a3e723a';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fix=row=>`<button class="text-link" data-fix-step="${row.step}" data-fix-floor="${e(row.floorId||'')}" data-fix-room="${e(row.roomId||'')}">去修改 →</button>`;
const list=(rows,empty)=>`<ul class="reading-list">${rows.length?rows.map(x=>`<li${x.roomId?` data-finding-room="${e(x.roomId)}"`:''}><b>${e(x.title)}</b><span>${e(x.text)}${x.role?` <em class="role-match">${e(x.role)}</em>`:''}</span></li>`).join(''):`<li class="muted">${e(empty)}</li>`}</ul>`;
const section=(n,name,good,bad,extra='')=>`<section class="report-section diagnostic-section" data-report-section="${n}"><span class="eyebrow">${n} / ${name}</span><h2>${name}</h2><h3 class="keep-heading">优点 · 建议保持</h3>${list(good,'现有资料尚不足以确认这一部分的优点。')}<h3 class="change-heading">缺点 · 建议修改</h3>${list(bad,'已提供资料中，未发现明确需要调整的项目。')}${extra}</section>`;
function grouped(h,items){const out=[];for(const x of items.map(x=>readingItem(h,x)).filter(x=>x.kind==='attention')){const key=x.caseKey+'-'+x.floorId+'-'+x.roomId;if(!out.some(y=>y.key===key))out.push({...x,key});}return out;}
export function personalRecommendations(b){const f=favorableReference(b),sleep=sleepingDirection(b);return `<section class="report-section personal-recommendations"><h2>推荐配色 · 三组选一</h2><small>${f.element?'按八字扶抑参考搭配':'出生资料未齐，以下为中性配色'}</small><div class="palette-options">${paletteGroups(f.element).map(([name,cs,names],i)=>`<article class="color-option"><h3>${i+1}. ${name}</h3><div class="color-trio">${cs.map((c,k)=>`<span><i style="background:${c}"></i>${names[k]}<small>${['窗帘 / 地毯','家具','抱枕 / 小件'][k]}</small></span>`).join('')}</div></article>`).join('')}</div><div class="sleep-direction"><h3>睡觉时头的朝向</h3><b>${sleep.directions.length?e(sleep.directions.join(' 或 ')):'补齐出生资料后给出方位'}</b><p>${sleep.directions.length?'床头优先靠实墙，避开窗下和门口直视；现场条件不合适，先保留安全、安静的床位。':'先保持床头靠实墙，避开窗下和门口直视。'}</p>${!sleep.directions.length?fix({step:0}):''}</div></section>`;}
export function renderReport(h,b,items,selected=[],saved){
 const missing=missingInputs(h,b),role=roleOf(h),external=externalFindings(h),groups=grouped(h,items),dirs=directionItems(h),notches=h.floors.map(f=>({f,data:boundaryNotches(f)}));
 const extGood=external.filter(x=>x.kind==='good'),extBad=external.filter(x=>x.kind!=='good').map(x=>({...x,text:x.text+(x.kind==='attention'?' '+x.action:'')}));
 if(!external.length)extBad.push({title:'宅外资料待补充',text:'先在免费地图查找楼栋，再到主要窗边核实遮挡、道路、噪声与视线。'});
 const cornerGood=notches.filter(x=>x.data.status==='checked'&&!x.data.items.length).map(({f})=>({title:f.name+' · 红线未见明显内凹',text:'保持封闭外墙边界，不把半封阳台或公共空间算入室内。'}));
 const cornerBad=notches.flatMap(({f,data})=>data.status==='missing'?[{title:f.name+' · 边界或方位未确认',text:'补齐封闭红线与八方位后，再判断内凹位置。'}]:data.items.map(x=>({title:`${f.name} · ${x.direction}${GUA[x.direction]||''}方内凹`,text:`本方红线内凹。${PALACES[x.direction]?.gua||''}卦家庭取象对应${PALACES[x.direction]?.person||'相应成员'}，重点查看相邻空间的采光、动线与使用条件。先核实凹处是不是管井或室外；处理方法见下方本宫解读。`,role:roleNote(h,x.direction)})));
 const internalGood=dirs.filter(x=>x.good.length).map(x=>({title:`${x.direction} · ${x.gua}卦 · ${x.want==='sand'?'砂':'水'}取象相合`,text:`已标${x.good.join('、')}。保留位置与使用空间，不为添摆件挤占通道。`,role:roleNote(h,x.direction)}));
 const internalBad=dirs.filter(x=>x.bad.length).map(x=>({title:`${x.direction} · ${x.gua}卦 · 砂水取象不对位`,text:`${x.bad.join('、')}与本方的${x.want==='sand'?'砂':'水'}取象相反。${x.locked?'固定设施保留原位，先处理附近拥挤和杂物。':'优先整理可动小件，再结合实际用途安排位置，不为取象搬动厨卫。'}`,role:roleNote(h,x.direction)}));
 const spaceGood=h.floors.flatMap(f=>f.rooms.filter(r=>['bedroom','study'].includes(r.type)).map(r=>({title:`${f.name} · ${r.name} · ${orient(roomAnchor(r),f)}`,text:r.type==='bedroom'?'休息用途明确。保持床边通路，工作资料收出休息区。':'已有固定专注区。保留桌面与集中收纳，休闲活动另留位置。'})));
 const spaceBad=groups.map(x=>({title:`${x.where} · ${x.title}`,text:x.why,roomId:x.roomId}));
 return `<div class="report-profile"><span>${e(role.name)}${role.direction?` · ${role.direction}${role.gua}方`:''}</span><span>${e(TIERS[h.tier].name)} · ${e(h.budget)}元以内${h.buildingFloor?` · 所在 ${e(h.buildingFloor)} 楼`:''}</span></div>${role.direction?'<p class="small-note">身份对应《说卦》的家庭方位，用来突出与你相关的位置。</p>':''}<details class="report-reference input-review" ${missing.length?'open':''}><summary>${missing.length?`判断前需核对 ${missing.length} 项资料`:'判断资料已齐备'}</summary><ol class="missing-links">${missing.map(x=>`<li><div><b>${e(x.title)}</b></div>${fix(x)}</li>`).join('')}</ol></details>
 ${section('01','外部风水',extGood,extBad,'<button class="text-link" data-action="report-environment">按门窗逐面补录 →</button>'+`<small class="source-note">${external.length?'来源：'+e([...new Set(external.map(x=>x.source))].join('、')):'地图地点需要现场核对；未自动导入地图数据。'}</small>`)}
 ${section('02','缺角',cornerGood,cornerBad,notches.some(x=>x.data.items.length)?fix({step:5}):'')}
 <section class="report-section diagnostic-section" data-report-section="03"><span class="eyebrow">03 / 内部风水</span><h2>内部风水 · 八方与中宫</h2>${renderPalaces(h)}<small class="source-note">卦象对应为传统文化解释；不是对家中有无成员或人生事件的事实判断。</small></section>
 ${section('04','空间风水',spaceGood,spaceBad)}
 ${personalRecommendations(b)}
 <section class="improvement-picker report-section"><span class="eyebrow">重点改善</span><h2>你希望加强哪几项？</h2><p>月满则亏，调整也要留有余地。最多选 3 项集中加强，其余缺点仍会给出基本改法。</p><div class="goal-grid">${Object.entries(GOALS).map(([k,v])=>`<button class="goal ${selected.includes(k)?'selected':''}" data-improve-goal="${k}" aria-pressed="${selected.includes(k)}">${v}</button>`).join('')}</div><small>已选 ${selected.length} / 3</small><button class="btn primary" data-action="improve-all" ${!selected.length?'disabled':''}>生成修改方案与图纸 →</button>${saved?.planId?`<button class="text-link" ${saved.revision===h.revision?'data-action="view-improvements"':`data-plan="${saved.planId}"`}>${saved.revision===h.revision?'查看已生成方案':'查看修改资料前的方案'} →</button>`:''}</section>`;
}
export function renderAdvice(h,b,saved){if(!saved||saved.revision!==h.revision)return '';const groups=grouped(h,saved.items),year=yearAdvice(h,saved.goals),ext=externalFindings(h),dirs=directionItems(h).filter(x=>x.bad.length);return `<div class="improvement-results"><div class="report-profile">加强：${saved.goals.map(x=>e(GOALS[x])).join('、')} · ${e(TIERS[h.tier].name)}</div><section class="report-section"><h2>01 / 外部风水 · 改法</h2>${ext.length?list(ext.map(x=>({...x,text:x.kind==='unknown'?x.text:x.action})), ''):'<p>先从主要窗边补录周边情况。公共道路和外部楼栋不能改动；确认实际干扰后，再调整屋内座位、窗帘和照明。</p>'}</section><section class="report-section"><h2>02 / 缺角 · 改法</h2>${list(h.floors.flatMap(f=>boundaryNotches(f).items.map(x=>({title:`${f.name} · ${x.direction}方`,text:'核实红线后，凹处内侧以低矮收纳顺墙摆放，转角留给通行。结构柱、管井及产权外空间保留；不要为“补角”封堵公共区域。',role:roleNote(h,x.direction)}))),'现有红线没有明显内凹，保留外墙与边界。')}</section><section class="report-section"><h2>03 / 内部风水 · 改法</h2>${list(dirs.map(x=>({title:`${x.direction}${x.gua}方 · ${x.bad.join('、')}`,text:x.locked?'固定设施不移动。清掉周边无用小件，先保证操作和通行；不为砂水取象迁移管线。':'先减少不必要的小件；床、沙发等主要家具按下方图纸在原房间内试摆。若实际位置更好，保留原位；不以摆件取代采光与通行。',role:roleNote(h,x.direction)})),'已标物件未触发相反取象，保持常用家具与通道。')}</section><section class="report-section"><h2>04 / 空间风水 · 改法</h2>${groups.map(x=>`<article class="reading-case" data-remedy="${e(x.id)}"><h3>${e(x.where)} · ${e(x.title)}</h3><p>${e(x.action)}</p>${x.tags.some(g=>saved.goals.includes(g))?`<p class="reading-boost">重点加强：${e(x.boost)}</p>`:''}</article>`).join('')||'<p>保留现有动静分区。下方图纸用于试摆已有家具，先核对开门和取物空间。</p>'}</section><section class="report-section year-reading"><h2>${year.year} 年 · 所选方向加强</h2><small>九宫年星取象，适用当年立春至次年立春。</small>${year.rows.map(x=>`<article><h3>${e(GOALS[x.goal])} · ${e(x.direction)} · ${e(x.star)}</h3><p>${e(x.action)}${x.rooms.length?`对应${e(x.rooms.join('、'))}。`:''}厨卫和通道保留原用途，陈设只放在可用边柜上。</p></article>`).join('')}</section></div>`;}
