import {GOALS,TIERS} from './core.js?v=f00a726325c4';
import {orient} from './deep.js?v=f00a726325c4';
import {roomAnchor} from './geometry.js?v=f00a726325c4';
import {favorableReference,paletteGroups} from './favorable.js?v=f00a726325c4';
import {missingInputs,directionItems,personalFit,yearAdvice,ELEMENT,GUA} from './report-data.js?v=f00a726325c4';
import {readingItem} from './report-copy.js?v=f00a726325c4';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fix(row){return `<button class="text-link" data-fix-step="${row.step}" data-fix-floor="${e(row.floorId||'')}" data-fix-room="${e(row.roomId||'')}">去修改 →</button>`;}
function colors(b){const f=favorableReference(b);return `<section class="report-section palette-card"><span class="eyebrow">06 / 喜用配色</span><h2>${f.element?`自动喜用参考：${e(f.element)}`:'喜用待核对，先选中性搭配'}</h2><p>${e(f.reason)}${f.element?'。以下按扶抑参考搭配，三组选一组即可。':'。以下三组用于过渡。'}</p><div class="palette-options">${paletteGroups(f.element).map(([name,cs,names],i)=>`<article class="color-option"><h3>${i+1}. ${name}</h3><div class="color-trio">${cs.map((c,k)=>`<span><i style="background:${c}"></i>${names[k]}<small>${['窗帘 / 地毯','家具','抱枕 / 小件'][k]}</small></span>`).join('')}</div><p>${names[0]}用于窗帘或地毯，${names[1]}接续家具，${names[2]}点缀抱枕；先试小样再购买。</p></article>`).join('')}</div></section>`;}
function fitSection(h,b){const fit=personalFit(h,b),f=fit.favored;if(!b||!f.element)return `<section class="report-section personal-fit"><span class="eyebrow">02 / 人宅契合</span><h2>${b?'喜用尚不能确定，暂不下契合结论':'缺少八字，暂不能判断人宅契合'}</h2><p>${e(f.reason)}。住宅优缺点继续列在下方。</p>${fix({step:0})}</section>`;
 const names=fit.aligned.map(r=>r.name).join('、'),title=fit.aligned.length?`${names}与本次喜用参考同类`:'现有主要房间未落在喜用同类方位';
 return `<section class="report-section personal-fit"><span class="eyebrow">02 / 人宅契合</span><h2>${e(title)}</h2><p>${e(f.reason)}。喜用参考取${e(f.element)}，${fit.aligned.length?`可优先在${e(names)}使用对应配色，保留当前用途`:'先通过织物配色补充，不必仅为方位调换房间'}。</p><ul class="reading-list">${fit.rooms.map(r=>{const el=ELEMENT[r.direction];return `<li><b>${e(r.name)} · ${e(r.direction)}${e(GUA[r.direction]||'')}宫</b><span>${el?`${el}行，${el===f.element?'与喜用参考同类，建议保持当前用途':'配色可按喜用协调，先保留实际使用安排'}`:'位于中部，保留通行空间'}${fit.map&&fit.map[r.direction]?`；八宅命卦对应${e(fit.map[r.direction])}`:''}。</span></li>`;}).join('')}</ul><p class="small-note">八宅星名为传统分类，不对应疾病、寿命或财务结果。</p></section>`;}
export function renderReport(h,b,items,selected,saved){const missing=missingInputs(h,b),read=items.map(x=>readingItem(h,x)),groups=[];for(const x of read.filter(x=>x.kind==='attention')){const key=x.caseKey+'-'+x.floorId+'-'+x.roomId,g=groups.find(g=>g.key===key);if(g)g.ids.push(x.id);else groups.push({...x,key,ids:[x.id]});}
 const dirs=directionItems(h),good=dirs.filter(x=>x.good.length),bad=dirs.filter(x=>x.bad.length),year=yearAdvice(h,saved?.goals||[]),strengths=h.floors.flatMap(f=>f.rooms.filter(r=>['bedroom','study'].includes(r.type)).map(r=>({f,r}))).slice(0,4);
 return `<section class="consultation-overview report-section"><span class="eyebrow">01 / 判断依据</span><h2>${missing.length?`先核对这 ${missing.length} 项资料`:'本次图面资料已齐备'}</h2>${missing.length?`<ol class="missing-links">${missing.map(x=>`<li><div><b>${e(x.title)}</b><p>${e(x.action)}</p></div>${fix(x)}</li>`).join('')}</ol>`:'<p>已包含边界、两边实测长度、功能区尺寸、门窗与八方位。</p>'}<p class="reading-budget">${e(TIERS[h.tier].name)} · 预算上限 ${e(h.budget)} 元</p></section>${fitSection(h,b)}
 <section class="report-section report-strengths"><span class="eyebrow">03 / 优点与保持</span><h2>这些安排可以保留</h2><p class="small-note">以下砂水为室内物件的传统取象。</p><ul class="reading-list">${good.map(x=>`<li><b>${e(x.direction)} · ${x.gua}卦 · ${x.want==='sand'?'砂':'水'}对位</b><span>已标${e(x.good.join('、'))}，与这一方的砂水偏好相符。保持现有位置，并留出通行与使用空间。</span></li>`).join('')}${strengths.map(({f,r})=>`<li><b>${e(r.name)} · ${e(orient(roomAnchor(r),f))}方</b><span>${r.type==='study'?'专注用途已经独立，保持工作资料集中收纳，减少卧室中的工作物品。':'已有明确休息区，保持床边通路与夜间安静，不为摆件占用床边。'}</span></li>`).join('')||'<li>现有资料还不足以列出可确认的优势，先完成上方核对。</li>'}</ul></section>
 <section class="report-section report-weaknesses"><span class="eyebrow">04 / 缺点与调整</span><h2>${groups.length||bad.length?'先处理这些不合适的安排':'现有标注未发现明确调整项'}</h2><ul class="reading-list">${bad.map(x=>`<li><b>${e(x.direction)} · ${x.gua}卦 · 砂水取象不对位</b><span>这一方取${x.want==='sand'?'砂':'水'}，图中${e(x.bad.join('、'))}为相反取象。${x.locked?'涉及固定或锁定物件，保留原位；先降低附近杂物与视觉拥挤。':'先整理或移动可动小件，不因这一条迁移厨卫或新增鱼缸。'}</span></li>`).join('')}${groups.map(x=>`<li data-finding-room="${e(x.roomId||'')}"><b>${e(x.where)} · ${e(x.title)}</b><span>${e(x.why)}</span></li>`).join('')}</ul></section>
 <section class="improvement-picker report-section"><span class="eyebrow">05 / 重点加强</span><h2>你希望重点改善什么？</h2><p>最多选三项。未选中的问题也会处理。</p><div class="goal-grid">${Object.entries(GOALS).map(([k,v])=>`<button class="goal ${selected.includes(k)?'selected':''}" data-improve-goal="${k}" aria-pressed="${selected.includes(k)}">${v}</button>`).join('')}</div><button class="btn primary" data-action="improve-all">${saved?'更新修改建议':'生成修改建议'}</button></section>
 <section class="improvement-results" data-enhanced="${!!saved}"><div class="reading-cases">${groups.map(x=>`<article class="reading-case report-section" data-remedy="${e(x.ids[0])}">${x.ids.slice(1).map(id=>`<span data-remedy="${e(id)}" hidden></span>`).join('')}<h3>${e(x.where)} · 修改方法</h3><p class="reading-action">${e(x.action)}</p>${saved&&x.tags.some(g=>saved.goals.includes(g))?`<p class="reading-boost">重点加强：${e(x.boost)}</p>`:''}${x.roomId?`<button class="text-link" data-locate="${e(x.roomId)}" data-locate-floor="${e(x.floorId)}">查看图中位置 ↗</button>`:''}</article>`).join('')}${read.filter(x=>x.kind==='unknown').map(x=>`<span data-remedy="${e(x.id)}" hidden></span>`).join('')}</div>
 ${saved?`<section class="report-section external-reading"><h3>外部条件：能改什么，不能改什么</h3>${h.environment?.status==='ready'?`<ul class="reading-list">${h.environment.items.slice(0,6).map(x=>`<li><b>${e(x.name)}</b><span>${Number.isFinite(x.bearing)?e(['北','东北','东','东南','南','西南','西','西北'][Math.round(x.bearing/45)%8])+'侧 · ':''}${x.distance?Math.round(x.distance)+' 米 · ':''}来自高德地图</span></li>`).join('')}</ul><p>公共道路与外部建筑不能改动。到主要窗边确认实际遮挡和干扰；确有噪声先改善门窗密封，确有直视先试纱帘，室内优先调整可移动座位。</p>`:'<p>周边资料未导入，暂不指定外部改法。公共道路与他人建筑不能改；先从家中主要门窗看实际干扰，遮挡视线用纱帘，减少强光用遮光帘，移动座位避开直视。</p>'}<p>属于自家产权范围的围挡或庭院，确认边界后再设计；${h.tier==='large'?'涉及结构的改动先核实承重、管线与施工条件。':'本次不动硬装，先用可撤回的家具与软装调整。'}</p></section><section class="report-section year-reading"><h3>${year.year} 年九宫飞星 · 所选方向</h3><p class="small-note">适用当年立春至次年立春；以下为年星取象。</p>${year.rows.map(x=>`<article><h4>${GOALS[x.goal]} · ${x.direction} · ${x.star}</h4><p>${e(x.action)}${x.rooms.length?`图中对应${e(x.rooms.join('、'))}。`:'在图中核对这一方后，再决定落位。'}若该处是厨卫或通道，保留原用途，把陈设放在邻近可用边柜。</p></article>`).join('')}</section>`:''}${colors(b)}</section>`;
}
