import {service} from './integrations.js?v=b1cae4b4be94';
import {VISION_VERSION,adoptVision} from './vision.js?v=b1cae4b4be94';
import {ROOMS} from './core.js?v=b1cae4b4be94';
import {CATALOG} from './catalog.js?v=b1cae4b4be94';
import {roomAnchor} from './geometry.js?v=b1cae4b4be94';
import {symbol} from './plan-symbols.js?v=b1cae4b4be94';
import {bindViewport} from './drawing-tools.js?v=b1cae4b4be94';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function editVision(f,{modal:openModal,save,toast,local,accessRequired=false}){
 const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
 const modal=(t,b,a)=>openModal(t,b,a,{className:'recognition-modal vision-modal'});
 let generation=0,token='',tab='rooms',outline=false,selected=new Set(),objects=new Set(),types={},names={};
 const manualButton='<button class="btn ghost" id="vision-local">本机线稿识别</button>';
 function consent(){modal('DeepSeek · 识别户型图',`<div class="vision-consent"><p>识别房间、门窗和家具，核对位置后再采用。</p><p>点击同意后，仅将本张户型图发送给 DeepSeek。不会发送八字、地址或宅档中的其他资料。图上已有的文字也会随图片发送。</p>${accessRequired?'<label class="field">测试口令<input type="password" id="vision-token" autocomplete="off" placeholder="由测试发起人提供"></label>':''}<small>房间轮廓和家具可能漏识或错位；尺寸及八方位仍需你确认。</small><p id="vision-feedback" role="alert"></p></div>`,`${manualButton}<button class="btn primary" id="vision-start">同意并识图</button>`);$('#vision-local').onclick=()=>{$('#modal').close();local();};$('#vision-start').onclick=()=>{token=$('#vision-token')?.value?.trim()||token;if(accessRequired&&!token){$('#vision-feedback').textContent='请填写测试口令。';return;}run();};}
 async function run(){const id=++generation,controller=new AbortController();modal('正在识别户型图',`<div class="recognition-status" data-vision-run="${id}" data-vision-status="loading" role="status"><span class="recognition-spinner"></span><h3>正在找出房间、门窗和家具</h3><p>通常需要几十秒，请保持页面打开。</p><small>关闭后不会把未确认的结果写入宅档。</small></div>`,'<button class="btn ghost" data-close>取消识图</button>');const d=$('#modal'),cancel=()=>controller.abort();d.addEventListener('close',cancel,{once:true});const current=()=>id===generation&&!controller.signal.aborted&&d.open&&!!d.querySelector(`[data-vision-run="${id}"]`);
 try{const result=await service('recognize-plan',{image:f.image,consent:true},{signal:controller.signal,token});if(!current())return;f.visionRecognition=result;selected=new Set();objects=new Set();outline=false;types={};names={};show();}catch(err){if(!current())return;modal('本次识图未完成',`<div data-vision-status="error" role="alert"><p>${e(err.message)}</p><small>已有红线、房间和家具保持不变。</small></div>`,`${manualButton}<button class="btn primary" id="vision-retry">重新尝试</button>`);$('#vision-local').onclick=()=>{$('#modal').close();local();};$('#vision-retry').onclick=consent;}finally{d.removeEventListener('close',cancel);}}
 function show(){const r=f.visionRecognition;
 modal('核对识图结果',`<div data-vision-status="review"><p class="hint">${r.candidates.length} 个房间 · ${r.objects.length} 处门窗家具。${r.rejected?'部分轮廓不完整，已略过。':''}</p><div class="drawing-viewport vision-viewport" data-aspect="${f.width/f.height}"><div class="drawing-sheet"><div class="vision-plan"><img src="${e(f.image)}" alt="当前户型图"><svg id="vision-overlay" viewBox="0 0 1000 1000" preserveAspectRatio="none"></svg></div></div><div class="zoom-controls"><button data-vision-zoom="out" data-zoom aria-label="缩小识图预览">−</button><button data-vision-zoom="reset" data-zoom>复位</button><button data-vision-zoom="in" data-zoom aria-label="放大识图预览">＋</button></div></div><small>双指放大，放大后可拖动查看。编号对应下方标注。</small><div class="vision-tabs"><button data-vision-tab="rooms" class="${tab==='rooms'?'active':''}">房间 ${r.candidates.length}</button><button data-vision-tab="objects" class="${tab==='objects'?'active':''}">门窗家具 ${r.objects.length}</button></div><div id="vision-items"></div><label class="check"><input id="vision-reviewed" type="checkbox">已核对所选位置，红线排除了半封阳台</label><p id="vision-feedback" class="recognition-feedback" role="alert" hidden></p><button class="text-link" id="vision-again">重新发送此图识别</button></div>`,`<button class="btn ghost" data-close>返回</button><button class="btn primary" id="vision-adopt" ${!r.candidates.length&&!r.objects.length&&!r.boundary?'disabled':''}>采用所选</button>`);
 const viewport=bindViewport($('.vision-viewport'),`vision-${f.id}`);viewport.reset();all('[data-vision-zoom]').forEach(b=>b.onclick=()=>b.dataset.visionZoom==='reset'?viewport.reset():viewport.zoom(b.dataset.visionZoom==='in'?1.35:1/1.35));
 function draw(){const point=ps=>ps.map(p=>`${p.x*1000},${p.y*1000}`).join(' ');$('#vision-overlay').innerHTML=`${(outline?r.boundary:f.boundary)||r.boundary?`<polygon class="recognized-boundary ${outline?'':'candidate'}" points="${point((outline?r.boundary:f.boundary)||r.boundary)}"/>`:''}${tab==='rooms'?r.candidates.map((c,i)=>{const p=roomAnchor(c);return `<polygon class="recognized-region ${selected.has(i)?'chosen':''}" points="${point(c.points)}"/><text x="${p.x*1000}" y="${p.y*1000}">R${i+1}</text>`;}).join(''):r.objects.map((o,i)=>`<g class="vision-object ${objects.has(i)?'chosen':''}"><rect x="${(o.x-o.width/2)*1000}" y="${(o.y-o.height/2)*1000}" width="${o.width*1000}" height="${o.height*1000}"/><text x="${o.x*1000}" y="${o.y*1000}">F${i+1}</text></g>`).join('')}`;}
 function items(){$('#vision-items').innerHTML=tab==='rooms'?`${r.boundary?`<label class="check"><input type="checkbox" id="vision-boundary" ${outline?'checked':''}>采用红色外轮廓${f.boundary?'（替换已有红线）':''}</label>`:'<p class="hint">未识别到可靠外边界，请先手动勾画红线。</p>'}${r.candidates.map((c,i)=>`<div class="vision-row"><label class="check"><input type="checkbox" data-vision-room="${i}" ${selected.has(i)?'checked':''}>R${i+1}</label><input data-vision-name="${i}" aria-label="R${i+1}房间名称" maxlength="24" value="${e(names[i]??c.name)}"><select data-vision-type="${i}" aria-label="R${i+1}房间用途">${Object.entries(ROOMS).map(([k,v])=>`<option value="${k}" ${k===(types[i]||c.type)?'selected':''}>${v}</option>`).join('')}</select></div>`).join('')||'<p>未识别到可用房间，可回到原图手动勾画。</p>'}`:r.objects.map((o,i)=>`<label class="check vision-object-row"><input type="checkbox" data-vision-object="${i}" ${objects.has(i)?'checked':''}>${symbol(o.type)}<span>F${i+1} · ${e(CATALOG[o.type]?.name||o.type)}</span></label>`).join('')||'<p>未识别到可用门窗家具，可回到软装页手动添加。</p>';
 $('#vision-boundary')?.addEventListener('change',ev=>{outline=ev.target.checked;draw();});all('[data-vision-room]').forEach(el=>el.onchange=()=>{el.checked?selected.add(+el.dataset.visionRoom):selected.delete(+el.dataset.visionRoom);draw();});all('[data-vision-object]').forEach(el=>el.onchange=()=>{el.checked?objects.add(+el.dataset.visionObject):objects.delete(+el.dataset.visionObject);draw();});all('[data-vision-name]').forEach(el=>el.oninput=()=>names[el.dataset.visionName]=el.value);all('[data-vision-type]').forEach(el=>el.onchange=()=>types[el.dataset.visionType]=el.value);draw();}
 all('[data-vision-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.visionTab;all('[data-vision-tab]').forEach(el=>el.classList.toggle('active',el===b));items();});$('#vision-again').onclick=consent;
 $('#vision-adopt').onclick=()=>{try{if(!$('#vision-reviewed').checked)throw Error('先核对图上位置，并勾选确认。');const effectiveTypes=Object.fromEntries(r.candidates.map((c,i)=>[i,types[i]||c.type]));const result=adoptVision(f,{indices:[...selected],objectIndices:[...objects],boundary:outline,types:effectiveTypes,names});save(result.floor);$('#modal').close();toast(`已加入 ${result.added} 个房间、${result.objectsAdded} 处门窗家具${result.skipped?`，跳过 ${result.skipped} 个重复标注`:''}。可在图上继续调整。`);}catch(err){$('#vision-feedback').hidden=false;$('#vision-feedback').textContent=err.message;}};items();
 }
 if(f.visionRecognition?.version===VISION_VERSION)show();else consent();
}
